name: Generate WebGPU Native Docset

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: apt install cmake doxygen build-essential

    - name: Generate Documentation
      run: make
